FROM ubuntu:16.04 

RUN apt-get update && apt-get install openssl wget php-xdebug iputils-ping -fy

RUN mkdir /etc/cron.d && touch /etc/crontab

ADD scripts /scripts

ARG TWITTER_CONSUMER_KEY
ARG TWITTER_CONSUMER_SECRET
ARG TWITTER_USER_TOKEN
ARG TWITTER_USER_SECRET
ARG DATABASE_PASSWORD
ARG TCAT_DATABASE_USER
ARG TCAT_DATABASE_PASSWORD
ARG TCAT_USER_USERNAME
ARG TCAT_USER_PASSWORD
ARG TCAT_ADMIN_USERNAME
ARG TCAT_ADMIN_PASSWORD
ARG TCAT_SELF_UPDATE
ARG STATUS_CAPTURE_MODE

ENV TWITTER_CONSUMER_KEY=$TWITTER_CONSUMER_KEY
ENV TWITTER_CONSUMER_SECRET=$TWITTER_CONSUMER_SECRET
ENV TWITTER_USER_TOKEN=$TWITTER_USER_TOKEN
ENV TWITTER_USER_SECRET=$TWITTER_USER_SECRET
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV TCAT_DATABASE_USER=$TCAT_DATABASE_USER
ENV TCAT_DATABASE_PASSWORD=$TCAT_DATABASE_PASSWORD
ENV TCAT_USER_USERNAME=$TCAT_USER_USERNAME
ENV TCAT_USER_PASSWORD=$TCAT_USER_PASSWORD
ENV TCAT_ADMIN_USERNAME=$TCAT_ADMIN_USERNAME
ENV TCAT_ADMIN_PASSWORD=$TCAT_ADMIN_PASSWORD
ENV TCAT_SELF_UPDATE=$TCAT_SELF_UPDATE
ENV STATUS_CAPTURE_MODE=$STATUS_CAPTURE_MODE

RUN /scripts/tcat-install-linux.sh

CMD ["/bin/bash"]

