#!/bin/bash

docker build -t tcat-php \
--build-arg TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY} \
--build-arg TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET} \
--build-arg TWITTER_USER_TOKEN=${TWITTER_USER_TOKEN} \
--build-arg TWITTER_USER_SECRET=${TWITTER_USER_SECRET} \
--build-arg DATABASE_PASSWORD=${DATABASE_PASSWORD} \
--build-arg TCAT_DATABASE_USER=${TCAT_DATABASE_USER} \
--build-arg TCAT_DATABASE_PASSWORD=${TCAT_DATABASE_PASSWORD} \
--build-arg TCAT_USER_USERNAME=${TCAT_USER_USERNAME} \
--build-arg TCAT_USER_PASSWORD=${TCAT_USER_PASSWORD} \
--build-arg TCAT_ADMIN_USERNAME=${TCAT_ADMIN_USERNAME} \
--build-arg TCAT_ADMIN_PASSWORD=${TCAT_ADMIN_PASSWORD} \
--build-arg TCAT_SELF_UPDATE=${TCAT_SELF_UPDATE} \
--build-arg STATUS_CAPTURE_MODE=${STATUS_CAPTURE_MODE} \
.
